[package]
name = "exif_"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
rfd = "0.17.2"
img-parts = "0.4.0"
